version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://mcq_user:mcq_pass@db:3306/mcq_battle
      - SECRET_KEY=dev_secret_key_sea_1_mcq_battle
      - JWT_SECRET_KEY=jwt_secret_key_sea_1_mcq_battle
      - ADMIN_USERNAME=jerin_admin
      - ADMIN_PASSWORD=Kikky@2026
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mcq_battle
      MYSQL_USER: mcq_user
      MYSQL_PASSWORD: mcq_pass
      MYSQL_ROOT_PASSWORD: root_password_123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
